from d4j_odc_pipeline.web_fetch import fetch_bug_report

print('='*60)
print('LIVE INTEGRATION TEST: JIRA (Apache LANG-304)')
print('='*60)
r = fetch_bug_report('https://issues.apache.org/jira/browse/LANG-304')
print(f'  source_type: {r.source_type}')
print(f'  status_code: {r.status_code}')
print(f'  duration_ms: {r.duration_ms}')
print(f'  content_length: {r.content_length}')
print(f'  error: {r.error}')
print(f'  url: {r.url}')
print(f'  content preview (first 300 chars):')
print(f'  {r.content[:300]}')
print()

print('='*60)
print('LIVE INTEGRATION TEST: GitHub Issue')
print('='*60)
r2 = fetch_bug_report('https://github.com/google/gson/issues/1057')
print(f'  source_type: {r2.source_type}')
print(f'  status_code: {r2.status_code}')
print(f'  duration_ms: {r2.duration_ms}')
print(f'  content_length: {r2.content_length}')
print(f'  error: {r2.error}')
print(f'  url: {r2.url}')
print(f'  content preview (first 300 chars):')
print(f'  {r2.content[:300]}')
print()

print('='*60)
print('LIVE INTEGRATION TEST: Error handling (invalid URL)')
print('='*60)
r3 = fetch_bug_report('https://nonexistent.invalid.tld/issue/123')
print(f'  source_type: {r3.source_type}')
print(f'  error: {r3.error}')
print(f'  content: [{r3.content}]')
print()

print('='*60)
print('LIVE INTEGRATION TEST: Empty URL')
print('='*60)
r4 = fetch_bug_report('')
print(f'  error: {r4.error}')
print()

print('ALL INTEGRATION TESTS COMPLETED')